import { chromium } from 'playwright';import fs from 'node:fs';
fs.mkdirSync('ui-evidence',{recursive:true});
const browser=await chromium.launch({headless:true});const page=await browser.newPage({viewport:{width:1220,height:780},reducedMotion:'reduce'});let requests=[];page.on('request',r=>requests.push(r.url()));let errors=[];page.on('pageerror',e=>errors.push(e.message));
for(let i=0;i<30;i++){try{await page.goto('http://127.0.0.1:8765');break}catch(e){if(i===29)throw e;await new Promise(r=>setTimeout(r,200));}}await page.getByRole('heading',{name:'Knowledge universe',exact:true}).waitFor();await page.getByRole('button',{name:'Team room',exact:true}).click();await page.screenshot({path:'ui-evidence/modern-chat.png'});
await page.getByRole('button',{name:'Team room',exact:true}).click();await page.getByRole('button',{name:'DEX Coder'}).click();await page.getByRole('heading',{name:'Knowledge universe',exact:true}).waitFor();await page.screenshot({path:'ui-evidence/modern-DEX-expression.png'});
await page.getByLabel('Settings',{exact:true}).click();await page.getByRole('button',{name:'Appearance',exact:true}).click();await page.getByLabel('Font selector').selectOption('Verdana');if(!(await page.locator('.app').evaluate(e=>getComputedStyle(e).fontFamily)).includes('Verdana'))throw Error('Font choice not applied');await page.getByRole('button',{name:'Team room',exact:true}).click();await page.getByLabel('Message draft').fill('Draft stays local.');await page.getByLabel('Send message').click();await page.getByText('Draft stays local.',{exact:true}).waitFor();await page.screenshot({path:'ui-evidence/modern-draft-font.png'});
await page.getByLabel('Settings',{exact:true}).click();await page.getByRole('button',{name:'Privacy',exact:true}).click();await page.getByRole('heading',{name:'Local sensing, explicit permission.'}).waitFor();if(!await page.getByRole('button',{name:'Allow local camera',exact:true}).isDisabled())throw Error('Sensor allowed without backend');await page.getByRole('button',{name:'Previous view',exact:true}).click();await page.getByRole('heading',{name:'Knowledge universe',exact:true}).waitFor();await page.getByLabel('Settings',{exact:true}).click();await page.getByRole('button',{name:'Appearance',exact:true}).click();await page.getByLabel('Workspace face size').selectOption('large');await page.reload();await page.getByLabel('Settings',{exact:true}).click();await page.getByRole('button',{name:'Appearance',exact:true}).click();if(await page.getByLabel('Workspace face size').inputValue()!=='large')throw Error('Face size not retained');await page.getByLabel('Workspace face size').selectOption('medium');await page.getByRole('button',{name:'Advanced',exact:true}).click();await page.getByRole('button',{name:'Pause all',exact:true}).click();await page.screenshot({path:'ui-evidence/modern-awareness-off.png'});
if(errors.length)throw Error(errors.join('\n'));if(requests.some(x=>!x.startsWith('http://127.0.0.1:8765')))throw Error('Unexpected external request');
await page.getByRole('button',{name:'Team room',exact:true}).click();
for(let i=0;i<18;i++){await page.getByLabel('Message draft').fill('Scroll test '+i+' '+('long line '.repeat(25)));await page.getByLabel('Send message').click()}
await page.setViewportSize({width:1044,height:740});const scroll=page.locator('.universe-chat .conversation');await scroll.evaluate(e=>e.scrollTop=0);await page.waitForTimeout(250);if(await scroll.evaluate(e=>e.scrollTop)>5)throw Error('Scroll jumps to bottom');const box=await page.getByLabel('Message draft').boundingBox();if(!box||box.y+box.height>740)throw Error('Composer not pinned');if(!await scroll.evaluate(e=>e.scrollHeight>e.clientHeight))throw Error('Conversation does not scroll');await page.screenshot({path:'ui-evidence/scroll-pinned-composer.png'});
fs.writeFileSync('ui-evidence/checks.json',JSON.stringify({platform:process.platform,scope:'web renderer only; no live backend or Tauri overlay',checks:['persona select','expression state','font selector','local draft','awareness off','pause','no external web requests','no page errors']},null,2));await browser.close();
