const $=id=>document.getElementById(id);let token='',claim='',stream=null,context=null,node=null,parts=[],count=0,rate=0,timer=null,url=null,abort=null,generation=0,sending=false;
const status=(text,hint='')=>{$('status').textContent=text;$('hint').textContent=hint;};
const secure=()=>location.protocol==='https:'&&window.isSecureContext;
async function request(path,body,signal){if(!secure())throw Error('Trusted HTTPS is required.');const r=await fetch(path,{method:'POST',credentials:'omit',cache:'no-store',redirect:'error',headers:{'Content-Type':'application/json',...(token?{'Authorization':'Bearer '+token}:{})},body:JSON.stringify(body),signal});if(!r.ok)throw Error('Laptop session unavailable. Reconnect locally.');return r.json();}
async function release(){clearTimeout(timer);timer=null;node?.disconnect();node=null;stream?.getTracks().forEach(t=>t.stop());stream=null;if(context){await context.close().catch(()=>{});context=null;}parts=[];count=0;$('finish').hidden=true;}
function clearPlayback(){$('reply').pause();$('reply').removeAttribute('src');$('reply').load();$('reply').hidden=true;if(url)URL.revokeObjectURL(url);url=null;}
function wav(chunks,sampleRate){const raw=new Float32Array(chunks.reduce((n,x)=>n+x.length,0));let i=0;for(const x of chunks){raw.set(x,i);i+=x.length;}const n=Math.floor(raw.length*16000/sampleRate);if(n<1600||n>480000)throw Error('Speak between0.1and30seconds.');const b=new ArrayBuffer(44+n*2),v=new DataView(b);const text=(at,s)=>[...s].forEach((c,k)=>v.setUint8(at+k,c.charCodeAt(0)));text(0,'RIFF');v.setUint32(4,36+n*2,true);text(8,'WAVE');text(12,'fmt ');v.setUint32(16,16,true);v.setUint16(20,1,true);v.setUint16(22,1,true);v.setUint32(24,16000,true);v.setUint32(28,32000,true);v.setUint16(32,2,true);v.setUint16(34,16,true);text(36,'data');v.setUint32(40,n*2,true);for(let j=0;j<n;j++){const p=j*sampleRate/16000,k=Math.floor(p),a=raw[k]||0,c=raw[Math.min(k+1,raw.length-1)]||0;v.setInt16(44+j*2,Math.max(-1,Math.min(1,a+(c-a)*(p-k)))*32767,true);}return new Uint8Array(b);}
function b64(bytes){let s='';for(let i=0;i<bytes.length;i+=8192)s+=String.fromCharCode(...bytes.subarray(i,i+8192));return btoa(s);}
async function pollPair(ticket){abort=new AbortController();for(let i=0;i<120&&ticket===generation;i++){const r=await request('/phone/pair-result',{claim},abort.signal);if(ticket!==generation)return;if(r.token){token=r.token;claim='';$('pair-panel').hidden=true;$('connection').textContent='Paired';$('talk').disabled=false;status('Ready to speak','Press Speak to allow your microphone for this turn.');return;}await new Promise(r=>setTimeout(r,1000));}throw Error('Pairing expired. Request a new code on your laptop.');}
$('pair').onclick=async()=>{if(!secure()){status('Trusted connection needed','Phone transport has not been configured. No microphone or connection started.');return;}$('pair').disabled=true;const ticket=++generation;try{const r=await request('/phone/pair',{code:$('pair-code').value,label:$('phone-label').value});if(ticket!==generation)return;$('pair-code').value='';claim=r.claim;status('Approve on your laptop','This phone label does not prove your identity.');await pollPair(ticket);}catch(e){if(ticket===generation)status('Not paired',e.message);}finally{$('pair').disabled=false;}};
$('talk').onclick=async()=>{const ticket=++generation;if(!token||!secure())return;$('talk').disabled=true;clearPlayback();let captured=null,captureContext=null;const cleanOwned=async()=>{captured?.getTracks().forEach(t=>t.stop());await captureContext?.close().catch(()=>{});if(stream===captured){stream=null;context=null;node?.disconnect();node=null;parts=[];count=0;clearTimeout(timer);timer=null;$('finish').hidden=true;}};try{captured=await navigator.mediaDevices.getUserMedia({audio:{channelCount:1,echoCancellation:true,noiseSuppression:true},video:false});if(ticket!==generation){await cleanOwned();return;}captureContext=new AudioContext();stream=captured;context=captureContext;rate=captureContext.sampleRate;await captureContext.audioWorklet.addModule('capture.js');if(ticket!==generation){await cleanOwned();return;}node=new AudioWorkletNode(captureContext,'jarvis-capture');node.port.onmessage=e=>{if(ticket!==generation)return;const x=e.data;if(count+x.length>rate*30)return;parts.push(x);count+=x.length;};const source=captureContext.createMediaStreamSource(captured);source.connect(node);node.connect(captureContext.destination);$('finish').hidden=false;status('Listening','Send voice when finished. Capture stops after30seconds.');timer=setTimeout(()=>void sendVoice(ticket),30000);}catch(e){await cleanOwned();if(ticket===generation){$('talk').disabled=false;status('Microphone unavailable','Allow microphone access on this trusted page, or stop the call.');}}};
async function sendVoice(ticket){if(ticket!==generation||!stream||sending)return;sending=true;$('finish').disabled=true;let bytes;try{bytes=wav(parts,rate);}catch(e){await release();sending=false;$('finish').disabled=false;status('No voice sent',e.message);$('talk').disabled=false;return;}await release();if(ticket!==generation){sending=false;$('finish').disabled=false;return;}status('JARVIS is replying','Local laptop models only. Stop clears this turn.');abort=new AbortController();try{await request('/phone/turn',{wav:b64(bytes)},abort.signal);for(let i=0;i<90&&ticket===generation;i++){const r=await request('/phone/reply',{},abort.signal);if(ticket!==generation)return;if(r.wav){if(typeof r.wav!=='string'||r.wav.length>2560200)throw Error('Invalid reply audio');const s=atob(r.wav),raw=Uint8Array.from(s,c=>c.charCodeAt(0));url=URL.createObjectURL(new Blob([raw],{type:'audio/wav'}));$('reply').src=url;$('reply').hidden=false;status('Reply ready','Tap play if your phone blocks automatic audio.');await $('reply').play().catch(()=>{});return;}await new Promise(r=>setTimeout(r,1000));}throw Error('Reply timed out; stop and reconnect.');}catch(e){if(ticket===generation)status('No reply',e.message);}finally{sending=false;$('finish').disabled=false;if(ticket===generation)$('talk').disabled=false;}}
$('finish').onclick=()=>void sendVoice(generation);
$('stop').onclick=async()=>{const previous=token;++generation;token='';claim='';abort?.abort();await release();clearPlayback();claim='';token='';$('talk').disabled=true;$('pair-panel').hidden=false;$('connection').textContent='Offline';status('Call stopped','Microphone and playback stopped. Pair again for another call.');if(previous&&secure())fetch('/phone/stop',{method:'POST',credentials:'omit',headers:{'Authorization':'Bearer '+previous}}).catch(()=>{});};
window.addEventListener('pagehide',()=>{if(token&&secure())fetch('/phone/stop',{method:'POST',credentials:'omit',keepalive:true,headers:{'Authorization':'Bearer '+token}}).catch(()=>{});++generation;abort?.abort();stream?.getTracks().forEach(t=>t.stop());context?.close();clearPlayback();token='';claim='';});
if(!secure())status('Phone transport not connected','This prepared page needs trusted HTTPS. No microphone or network starts.');
