import React,{useEffect,useState}from'react';
export type FaceState='idle'|'thinking'|'speaking';
type Clip={fps:number,frames:string[]};
type Pack={version:1,width:number,height:number,personas:Record<string,Record<FaceState,Clip>>};
function database():Promise<IDBDatabase>{return new Promise((resolve,reject)=>{const request=indexedDB.open('jarvis-face-art',1);request.onupgradeneeded=()=>request.result.createObjectStore('packs');request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(Error('Face storage unavailable.'));});}
async function savedPack(value?:{pack:Pack,files:Record<string,Blob>}):Promise<{pack:Pack,files:Record<string,Blob>}|null>{const db=await database();return new Promise((resolve,reject)=>{const tx=db.transaction('packs',value?'readwrite':'readonly'),store=tx.objectStore('packs');const request=value?store.put(value,'selected'):store.get('selected');tx.oncomplete=()=>{db.close();resolve(value||request.result||null)};tx.onerror=()=>{db.close();reject(Error('Face pack could not be saved. Existing choice preserved.'))};});}
function apply(p:Pack,files:Record<string,Blob>){const map:Record<string,string>={};for(const [name,file]of Object.entries(files))map[name]=URL.createObjectURL(file);for(const u of Object.values(urls))if(u.startsWith('blob:'))URL.revokeObjectURL(u);urls=map;pack=p;listeners.forEach(fn=>fn());}
const channel=new BroadcastChannel('jarvis-face-pack');channel.onmessage=e=>{if(e.data?.request){if(pack)channel.postMessage({pack,urls});return;}try{validate(e.data.pack);pack=e.data.pack;urls=e.data.urls;listeners.forEach(fn=>fn())}catch{}};channel.postMessage({request:true});
let pack:Pack|null=null;let urls:Record<string,string>={};let listeners=new Set<()=>void>();
function validate(p:Pack){if(p.version!==1||p.width<64||p.width>1024||p.height!==p.width)throw Error('Use square64-1024px face frames.');for(const n of ['JARVIS','NOVA','KAI','LYRA','DEX'])for(const s of ['idle','thinking','speaking']as FaceState[]){const c=p.personas?.[n]?.[s];if(!c||c.fps<1||c.fps>30||!c.frames?.length||c.frames.length>120||c.frames.some(f=>!f||f.includes('..')||f.startsWith('/')||f.includes(':')))throw Error('Invalid face clip '+n+'/'+s);}}
export async function importFacePack(files:FileList){const all=Array.from(files);if(all.reduce((n,f)=>n+f.size,0)>60*1024*1024)throw Error('Face pack must stay under60MB.');const manifest=all.find(f=>f.name==='manifest.json');if(!manifest)throw Error('manifest.json is missing.');const p=JSON.parse(await manifest.text())as Pack;validate(p);const filesByName:Record<string,Blob>={};for(const f of all){if(!/^image\/(png|webp)$/.test(f.type))continue;const name=f.webkitRelativePath.split('/').slice(1).join('/')||f.name;filesByName[name]=f;}for(const n of Object.keys(p.personas))for(const c of Object.values(p.personas[n]))for(const f of c.frames)if(!filesByName[f])throw Error('Missing frame '+f);await savedPack({pack:p,files:filesByName});apply(p,filesByName);channel.postMessage({pack,urls});}
let imported=false;
savedPack().then(saved=>{if(saved){validate(saved.pack);apply(saved.pack,saved.files);imported=true;}}).catch(()=>{});
fetch('faces/manifest.json').then(r=>r.ok?r.json():null).then(p=>{if(p&&!imported){validate(p);pack=p;listeners.forEach(fn=>fn());}}).catch(()=>{});
export function FaceArt({persona,state,className,fallback}:{persona:string,state:string,className:string,fallback:React.ReactNode}){const[tick,setTick]=useState(0),[rev,setRev]=useState(0);useEffect(()=>{const cb=()=>setRev(x=>x+1);listeners.add(cb);return()=>{listeners.delete(cb)}},[]);const clip=pack?.personas[persona]?.[(state==='speaking'||state==='thinking'?state:'idle')as FaceState];useEffect(()=>{setTick(0);if(!clip)return;const timer=setInterval(()=>setTick(x=>x+1),1000/clip.fps);return()=>clearInterval(timer)},[clip,rev]);if(!clip)return <>{fallback}</>;const frame=clip.frames[tick%clip.frames.length];return <img className={className+' face-art'} src={urls[frame]||('faces/'+frame)} alt={persona+' '+state+' face'} draggable={false}/>;}
