"""Local editable SVG text-poster draft. Not a Canva integration or publication."""
import copy,hashlib,html,textwrap,time,uuid
class DesignDraft:
 def __init__(self,root,clock=time.monotonic):self.root=root;self.clock=clock;self.pending=None;self.deadline=0;self.result=None;self.status='Local design draft off; no Canva account'
 @staticmethod
 def wrap(text,width):
  return [line for paragraph in text.split('\n')for line in (textwrap.wrap(paragraph,width=width,replace_whitespace=True)or[''])]
 @staticmethod
 def validate(facts):
  if not isinstance(facts,dict)or set(facts)!={'title','body','footer','theme'}:raise ValueError('Exact poster title/body/footer/theme required')
  for key,limit in (('title',80),('body',600),('footer',100)):
   value=facts[key]
   if not isinstance(value,str)or len(value)>limit or any(ord(x)<32 and x!='\n'for x in value):raise ValueError('Bounded plain design text required')
  if not facts['title'].strip()or not facts['body'].strip():raise ValueError('Poster title and body required')
  if facts['theme']not in ('paper','midnight'):raise ValueError('Choose paper or midnight theme')
  # Deliberately conservative text layout, no truncation or hidden overflow.
  if len(DesignDraft.wrap(facts['title'],15))>4 or len(DesignDraft.wrap(facts['body'],28))>14 or len(DesignDraft.wrap(facts['footer'],28))>3:raise ValueError('Text exceeds poster layout; shorten it before review')
  return copy.deepcopy(facts)
 @staticmethod
 def render(facts):
  f=DesignDraft.validate(facts);bg,ink,accent=('#f4efec','#251f21','#527b6f')if f['theme']=='paper'else('#142329','#f4efec','#9bccc0')
  def lines(text,width,y,size,lineheight,weight):
   return ''.join('<text x="84" y="'+str(y+i*lineheight)+'" font-size="'+str(size)+'" font-weight="'+str(weight)+'">'+html.escape(line,quote=True)+'</text>'for i,line in enumerate(DesignDraft.wrap(text,width)))
  return '<svg xmlns="http://www.w3.org/2000/svg" width="1080" height="1350" viewBox="0 0 1080 1350"><title>'+html.escape(f['title'])+'</title><desc>Local text design draft. Not generated by or synced to Canva. Provided wording, not verified facts.</desc><rect width="1080" height="1350" fill="'+bg+'"/><rect x="84" y="92" width="96" height="8" fill="'+accent+'"/><g fill="'+ink+'" font-family="Arial, sans-serif">'+lines(f['title'],15,206,60,74,600)+lines(f['body'],28,540,32,43,400)+lines(f['footer'],28,1208,26,34,400)+'</g></svg>'
 def prepare(self,facts,consent=False):
  self.cancel()
  if consent is not True:raise ValueError('Review local design wording and style first')
  f=self.validate(facts);svg=self.render(f);self.pending={'review_id':uuid.uuid4().hex,'facts':f,'svg':svg,'sha256':hashlib.sha256(svg.encode()).hexdigest(),'size':'1080 x 1350','scope':'Editable local SVG text poster only. No Canva account, generated image, external assets, sync, automatic opening or publication.'};self.deadline=self.clock()+120;self.status='Review exact local design and wording';return copy.deepcopy(self.pending)
 def save(self,reviewed,confirm=False):
  if confirm is not True or not self.pending or reviewed!=self.pending or self.clock()>=self.deadline:raise ValueError('Review exact current local design before saving')
  svg=self.render(self.pending['facts'])
  if hashlib.sha256(svg.encode()).hexdigest()!=self.pending['sha256']:raise ValueError('Design review changed')
  if self.root.is_symlink():raise ValueError('Design draft folder must not be a link')
  self.root.mkdir(parents=True,exist_ok=True);p=self.root/('poster-'+self.pending['review_id']+'.svg')
  with p.open('x',encoding='utf-8')as stream:stream.write(svg)
  if p.read_text(encoding='utf-8')!=svg:raise ValueError('Saved design readback mismatch')
  self.result={'path':str(p),'sha256':self.pending['sha256'],'scope':self.pending['scope']};self.pending=None;self.deadline=0;self.status='Local editable SVG saved and read back; not opened or published';return copy.deepcopy(self.result)
 def cancel(self):self.pending=None;self.deadline=0;self.status='Design draft stopped; saved file unchanged'
 def snapshot(self):return {'pending':copy.deepcopy(self.pending)if self.clock()<self.deadline else None,'result':copy.deepcopy(self.result),'status':self.status,'scope':'Local design draft alternative, not Canva parity'}
